.catalog:
  name: Shadowsocks Server
  version: v0.0.1
  description: Easy shadowsocks server built with bluebu/shadowsocks-server image
  questions:
    - variable: SERVER_ADDR
      description: Server Address
      label: SERVER_ADDR
      type: string
      required: true
      default: 0.0.0.0
    - variable: PUBLIC_PORT
      description: Public Port
      label: PUBLIC_PORT
      type: "int"
      required: true
      default: 8899
    - variable: PASSWORD
      description: Service Password
      label: PASSWORD
      type: "password"
      required: true
    - variable: WORKERS
      description: Workers count
      label: WORKERS
      required: true
      default: 2
      type: enum   
      options: 
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
server:
  scale: 1